-- My Task Force V1 - Supabase schema
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null check (category in ('Home','Office','Outside','Personal Goals')),
  priority text not null default 'normal' check (priority in ('normal','urgent')),
  description varchar(300) default '',
  due_at timestamptz null,
  status text not null default 'todo' check (status in ('todo','completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz null
);

alter table public.tasks enable row level security;

-- Personal single-user V1:
-- The Streamlit app uses the Supabase anon key, so create policies that allow
-- access to the tasks table. For stronger security, replace these with
-- authenticated-user policies when login is upgraded.
create policy "allow anon read tasks"
on public.tasks for select to anon using (true);

create policy "allow anon insert tasks"
on public.tasks for insert to anon with check (true);

create policy "allow anon update tasks"
on public.tasks for update to anon using (true) with check (true);

create policy "allow anon delete tasks"
on public.tasks for delete to anon using (true);
